package br.fesa.ec7.markettracker.utils;

public class Utilitarios {
	
	public static String jsonTeste = "[\r\n"
			+ "  {\r\n"
			+ "    \"id\": 2,\r\n"
			+ "    \"iD_MERCADO\": 2,\r\n"
			+ "    \"iD_PRODUTO\": 1,\r\n"
			+ "    \"datA_HORA_REGISTRO\": \"2022-09-12T18:56:49.88\",\r\n"
			+ "    \"preco\": 5.45,\r\n"
			+ "    \"mercado\": {\r\n"
			+ "      \"id\": 2,\r\n"
			+ "      \"nome\": \"Atacadão\"\r\n"
			+ "    },\r\n"
			+ "    \"produto\": {\r\n"
			+ "      \"id\": 1,\r\n"
			+ "      \"nome\": \"Cerveja Heineken 330ml\",\r\n"
			+ "      \"coD_BARRAS\": \"          \"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"id\": 1,\r\n"
			+ "    \"iD_MERCADO\": 1,\r\n"
			+ "    \"iD_PRODUTO\": 1,\r\n"
			+ "    \"datA_HORA_REGISTRO\": \"2022-09-12T18:56:49.88\",\r\n"
			+ "    \"preco\": 5.70,\r\n"
			+ "    \"mercado\": {\r\n"
			+ "      \"id\": 1,\r\n"
			+ "      \"nome\": \"Carrefour\"\r\n"
			+ "    },\r\n"
			+ "    \"produto\": {\r\n"
			+ "      \"id\": 1,\r\n"
			+ "      \"nome\": \"Cerveja Heineken 330ml\",\r\n"
			+ "      \"coD_BARRAS\": \"          \"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"id\": 3,\r\n"
			+ "    \"iD_MERCADO\": 3,\r\n"
			+ "    \"iD_PRODUTO\": 1,\r\n"
			+ "    \"datA_HORA_REGISTRO\": \"2022-09-12T18:56:49.88\",\r\n"
			+ "    \"preco\": 6.00,\r\n"
			+ "    \"mercado\": {\r\n"
			+ "      \"id\": 3,\r\n"
			+ "      \"nome\": \"Americanas\"\r\n"
			+ "    },\r\n"
			+ "    \"produto\": {\r\n"
			+ "      \"id\": 1,\r\n"
			+ "      \"nome\": \"Cerveja Heineken 330ml\",\r\n"
			+ "      \"coD_BARRAS\": \"          \"\r\n"
			+ "    }\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"id\": 9,\r\n"
			+ "    \"iD_MERCADO\": 5,\r\n"
			+ "    \"iD_PRODUTO\": 1,\r\n"
			+ "    \"datA_HORA_REGISTRO\": \"2022-09-13T17:20:35.783\",\r\n"
			+ "    \"preco\": 6.00,\r\n"
			+ "    \"mercado\": {\r\n"
			+ "      \"id\": 5,\r\n"
			+ "      \"nome\": \"Tenda\"\r\n"
			+ "    },\r\n"
			+ "    \"produto\": {\r\n"
			+ "      \"id\": 1,\r\n"
			+ "      \"nome\": \"Cerveja Heineken 330ml\",\r\n"
			+ "      \"coD_BARRAS\": \"          \"\r\n"
			+ "    }\r\n"
			+ "  }\r\n"
			+ "]";

}
